//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoPreferencias
    {
        public GrupoPreferencias()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Preferencia = new HashSet<Preferencia>();
        }
    
        public int IdGrupo { get; set; }
        public string IdPreferencia { get; set; }
    
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<Preferencia> Preferencia { get; set; }
    }
}
