//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredienteReceta
    {
        public IngredienteReceta()
        {
            this.Ingrediente = new HashSet<Ingrediente>();
            this.Receta = new HashSet<Receta>();
        }
    
        public int id { get; set; }
        public string tipoIngrediente { get; set; }
        public short ingredienteID { get; set; }
        public short recetaID { get; set; }
    
        public virtual ICollection<Ingrediente> Ingrediente { get; set; }
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
