//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferencia
    {
        public Preferencia()
        {
            this.DietasExcluidas = new HashSet<DietasExcluidas>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public int UsuarioPreferenciaIdUsuario { get; set; }
    
        public virtual UsuarioPreferencia UsuarioPreferencia { get; set; }
        public virtual GrupoPreferencias GrupoPreferencias { get; set; }
        public virtual ICollection<DietasExcluidas> DietasExcluidas { get; set; }
    }
}
