//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioReceta
    {
        public UsuarioReceta()
        {
            this.Usuario = new HashSet<Usuario>();
            this.Receta = new HashSet<Receta>();
        }
    
        public int IdUsuario { get; set; }
        public string IdReceta { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
