//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes
    {
        public Ingredientes()
        {
            this.IngredientesRecetas = new HashSet<IngredientesRecetas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Porcion { get; set; }
        public decimal CaloriasPorcion { get; set; }
        public int PreferenciaId { get; set; }
    
        public virtual Preferencias Preferencias { get; set; }
        public virtual ICollection<IngredientesRecetas> IngredientesRecetas { get; set; }
    }
}
