//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPDDS_BDEntities1 : DbContext
    {
        public TPDDS_BDEntities1()
            : base("name=TPDDS_BDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calificaciones> Calificaciones { get; set; }
        public virtual DbSet<Clasificaciones> Clasificaciones { get; set; }
        public virtual DbSet<Complexiones> Complexiones { get; set; }
        public virtual DbSet<CondicionesPreexistentes> CondicionesPreexistentes { get; set; }
        public virtual DbSet<Condimentos> Condimentos { get; set; }
        public virtual DbSet<Dietas> Dietas { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Ingredientes> Ingredientes { get; set; }
        public virtual DbSet<IngredientesRecetas> IngredientesRecetas { get; set; }
        public virtual DbSet<PiramideAlimenticia> PiramideAlimenticia { get; set; }
        public virtual DbSet<Preferencias> Preferencias { get; set; }
        public virtual DbSet<Procedimientos> Procedimientos { get; set; }
        public virtual DbSet<Recetas> Recetas { get; set; }
        public virtual DbSet<Rutinas> Rutinas { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<Temporadas> Temporadas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
