//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferencias
    {
        public Preferencias()
        {
            this.Ingredientes = new HashSet<Ingredientes>();
            this.Dietas = new HashSet<Dietas>();
            this.Grupos = new HashSet<Grupos>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Ingredientes> Ingredientes { get; set; }
        public virtual ICollection<Dietas> Dietas { get; set; }
        public virtual ICollection<Grupos> Grupos { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
