//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public Recetas()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
            this.IngredientesRecetas = new HashSet<IngredientesRecetas>();
            this.Procedimientos = new HashSet<Procedimientos>();
            this.Clasificaciones = new HashSet<Clasificaciones>();
            this.Condimentos = new HashSet<Condimentos>();
            this.Temporadas = new HashSet<Temporadas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Dificultad { get; set; }
        public decimal TotalCalorias { get; set; }
        public int PiramideId { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        public virtual ICollection<IngredientesRecetas> IngredientesRecetas { get; set; }
        public virtual PiramideAlimenticia PiramideAlimenticia { get; set; }
        public virtual ICollection<Procedimientos> Procedimientos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Clasificaciones> Clasificaciones { get; set; }
        public virtual ICollection<Condimentos> Condimentos { get; set; }
        public virtual ICollection<Temporadas> Temporadas { get; set; }
    }
}
