//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public Calificacion()
        {
            this.ClasificacionReceta = new HashSet<ClasificacionReceta>();
        }
    
        public int Id { get; set; }
        public short Valor { get; set; }
        public short UsuarioID { get; set; }
    
        public virtual ICollection<ClasificacionReceta> ClasificacionReceta { get; set; }
    }
}
