//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloContainer : DbContext
    {
        public ModeloContainer()
            : base("name=ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calificacion> CalificacionConjunto { get; set; }
        public DbSet<Clasificacion> ClasificacionConjunto { get; set; }
        public DbSet<Complexion> ComplexionConjunto { get; set; }
        public DbSet<CondicionPreexistente> CondicionPreexistenteConjunto { get; set; }
        public DbSet<Condimento> CondimentoConjunto { get; set; }
        public DbSet<Dieta> DietaConjunto { get; set; }
        public DbSet<Grupo> GrupoConjunto { get; set; }
        public DbSet<Ingrediente> IngredienteConjunto { get; set; }
        public DbSet<IngredienteReceta> IngredienteRecetaConjunto { get; set; }
        public DbSet<PiramideAlimenticia> PiramideAlimenticiaConjunto { get; set; }
        public DbSet<Preferencia> PreferenciaConjunto { get; set; }
        public DbSet<Procedimiento> ProcedimientoConjunto { get; set; }
        public DbSet<Receta> RecetaConjunto { get; set; }
        public DbSet<Temporada> TemporadaConjunto { get; set; }
        public DbSet<Usuario> UsuarioConjunto { get; set; }
        public DbSet<UsuarioPreferencia> UsuarioPreferenciaConjunto { get; set; }
        public DbSet<UsuarioReceta> UsuarioRecetaConjunto { get; set; }
        public DbSet<UsuarioGrupo> UsuarioGrupoConjunto { get; set; }
        public DbSet<GrupoPreferencias> GrupoPreferenciasConjunto { get; set; }
        public DbSet<CondimentoReceta> CondimentoRecetaConjunto { get; set; }
        public DbSet<ClasificacionReceta> ClasificacionRecetaConjunto { get; set; }
        public DbSet<DietasExcluidas> DietasExcluidasConjunto { get; set; }
    }
}
