//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.CondicionPreexistente = new HashSet<CondicionPreexistente>();
            this.Dieta = new HashSet<Dieta>();
        }
    
        public int Id { get; set; }
        public string userName { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public string FechaDeNacimiento { get; set; }
        public string FechaAltaPerfil { get; set; }
        public string Altura { get; set; }
        public string Rutina { get; set; }
        public string CondicionPreexistenteID { get; set; }
        public string ComplexionID { get; set; }
        public string DietaID { get; set; }
        public int UsuarioRecetaIdUsuario { get; set; }
    
        public virtual UsuarioReceta UsuarioReceta { get; set; }
        public virtual UsuarioGrupo UsuarioGrupo { get; set; }
        public virtual UsuarioPreferencia UsuarioPreferencia { get; set; }
        public virtual ICollection<CondicionPreexistente> CondicionPreexistente { get; set; }
        public virtual Complexion Complexion { get; set; }
        public virtual ICollection<Dieta> Dieta { get; set; }
    }
}
