//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioGrupo
    {
        public UsuarioGrupo()
        {
            this.Usuario = new HashSet<Usuario>();
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int IdUsuario { get; set; }
        public string IdGrupo { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
