//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietasExcluidas
    {
        public DietasExcluidas()
        {
            this.Dieta = new HashSet<Dieta>();
        }
    
        public int Id_Dieta { get; set; }
        public short Id_preferencia { get; set; }
    
        public virtual ICollection<Dieta> Dieta { get; set; }
        public virtual Preferencia Preferencia { get; set; }
    }
}
