//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public short porcion { get; set; }
        public short caloriasPorcion { get; set; }
        public int IngredienteReceta_id { get; set; }
    
        public virtual IngredienteReceta IngredienteReceta { get; set; }
    }
}
