//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public Receta()
        {
            this.Procedimiento = new HashSet<Procedimiento>();
            this.Temporada = new HashSet<Temporada>();
            this.Clasificacion = new HashSet<Clasificacion>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public short dificultad { get; set; }
        public double totalCalorias { get; set; }
        public string piramideID { get; set; }
        public string usuarioID { get; set; }
        public int UsuarioRecetaIdUsuario { get; set; }
        public int CondimentoRecetaIdReceta { get; set; }
        public int IngredienteReceta_id { get; set; }
    
        public virtual UsuarioReceta UsuarioReceta { get; set; }
        public virtual ClasificacionReceta ClasificacionReceta { get; set; }
        public virtual CondimentoReceta CondimentoReceta { get; set; }
        public virtual IngredienteReceta IngredienteReceta { get; set; }
        public virtual ICollection<Procedimiento> Procedimiento { get; set; }
        public virtual ICollection<Temporada> Temporada { get; set; }
        public virtual ICollection<Clasificacion> Clasificacion { get; set; }
    }
}
