// <auto-generated />
namespace TP_DDS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class GrupoUsuEliminado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GrupoUsuEliminado));
        
        string IMigrationMetadata.Id
        {
            get { return "201511260427593_GrupoUsuEliminado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
