// <auto-generated />
namespace TP_DDS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class userBajaID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userBajaID));
        
        string IMigrationMetadata.Id
        {
            get { return "201511260349099_userBajaID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
